name: Test4

on:
  workflow_run:
    workflows: ["Test3"]
    types:
      - completed
    branches:
      - main
      - develop
      - experimental/*
      - release/*
      - feature/add_github_actions

jobs:
  on-success4:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        run: echo "hello world"


