name: Test6

on:
  workflow_run:
    workflows: ["Test5"]
    types:
      - completed
    branches:
      - master

jobs:
  on-success6:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        run: echo "hello world"


